application: oh-the-humanity
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /game\.html
  static_files: game.html
  upload: game\.html

- url: /css/game\.css
  static_files: css/game.css
  upload: css/game\.css

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
