application: oh-the-humanity
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /game
  static_files: html/game.html
  upload: html/game.html

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)

- url: /lib/angular/(.*)
  static_files: lib/angular/\1
  upload: lib/angular/(.*)

- url: /partials/(.*)
  static_files: partials/\1
  upload: partials/(.*)

libraries:
- name: webapp2
  version: "2.5.1"
