application: oh-the-humanity
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(game|join_game|create_game)
  static_files: html/\1.html
  upload: html/(game|join_game|create_game).html

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)

- url: /lib/angular/(.*)
  static_files: lib/angular/\1
  upload: lib/angular/(.*)

- url: /partials/(.*)
  static_files: partials/\1
  upload: partials/(.*)

- url: /creategame
  script: create_game_handler.app

- url: /joingame
  script: join_game_handler.app

- url: /gamestate
  script: game_state_handler.app

- url: /
  static_files: html/welcome.html
  upload: html/welcome.html

libraries:
- name: webapp2
  version: "2.5.1"
